### ISSUE TITLE
SMS List segfault Asterisk

### ISSUE THREAD

**Issue by stich86** [RoEdAl/asterisk-chan-quectel#16]
hi @RoEdAl,

i'm playing with SMS, looks like each command  `quectel sms list`  will make Asterisk segfault:

```
[158870.080522] asterisk[20190]: segfault at 0 ip 00007f941a13a283 sp 00007f9416021f68 error 4 in libc.so[7f941a137000+4c000]
[158870.081749] Code: b6 03 84 c0 75 f1 48 89 d8 5b c3 0f 1f 40 00 67 e8 42 03 00 00 48 01 c3 48 89 d8 5b c3 66 2e 0f 1f 84 00 00 00 00 00 0f b6 17 <0f> b6 0e b8 01 00 00 00 38 d1 74 1a eb 27 0f 1f 80 00 00 00 00 0f
```

any idea?

**Comment by RoEdAl** [comment]
* What exactly command you are trying to execute: `quectel sms list all`, `quectel sms list received unread` or `quectel sms list received read`?
* What module you're using?
* Please show me more logs right after command invocation at level five if you can.

**Comment by stich86** [comment]
> * What exactly command you are trying to execute: `quectel sms list all`, `quectel sms list received unread` or `quectel sms list received read`?
> * What module you're using?
> * Please show me more logs right after command invocation at level five if you can.

Here is the output (same behaviour for all three commands)

```
Connected to Asterisk 20.5.2 currently running on OpenWrt (pid = 24931)
OpenWrt*CLI> core set verbose 5
Console verbose was 4 and is now 5.
OpenWrt*CLI> quectel sms list received
No such command 'quectel sms list received ' (type 'core show help quectel sms list received' for other possible commands)
OpenWrt*CLI> quectel sms list received
read    unread
OpenWrt*CLI> quectel sms list received read
OpenWrt*CLI>
Disconnected from Asterisk server
Asterisk cleanly ending (0).
Executing last minute cleanups
```

Here is the module used:

```
OpenWrt*CLI> quectel show device state quectel0
-------------- Status -------------
  Device                  : quectel0
  State                   : Free
  Audio                   : /dev/ttyUSB1
  Data                    : /dev/ttyUSB2
  Voice                   : Yes
  SMS                     : No
  Manufacturer            : Quectel
  Model                   : RM502Q-GL
  Firmware                : RM502QGLAAR11A02M4G
  IMEI                    : XXXXXX
  IMSI                    : XXXXXX
  ICCID                   : XXXXXX
  GSM Registration Status : Registered, home network
  RSSI                    : 22, -69 dBm
  Access technology       : LTE
  Network Name            : ho.
  Short Network Name      : ho.
  Registered PLMN         : 22210
  Provider Name           : ho.
  Band                    : LTE BAND 3
  Location area code      : 80EB
  Cell ID                 : 10F7520
  Subscriber Number       : Unknown
  SMS Service Center      : +393770001016
  Tasks in queue          : 0
  Commands in queue       : 0
  Call Waiting            : Off
  Current device state    : start
  Desired device state    : start
  When change state       : now
  Calls/Channels          : 0
    Active                : 0
    Held                  : 0
    Dialing               : 0
    Alerting              : 0
    Incoming              : 0
    Waiting               : 0
    Releasing             : 0
    Initializing          : 0
```

the send command works without any issue

**Comment by RoEdAl** [comment]
Have you invoked command without specifying a device - i.e. `quectel sms list received read` instead of `quectel sms list received read quectel0`?

**Comment by RoEdAl** [comment]
Crashing is a bug of course and should be fixed (hopefully) soon. At minimum `chan_quectel` should just report missing parameter. But you're right - if no device is specified then command may be addressed to all devices.

**Comment by stich86** [comment]
good to know :)
thanks for your amazing work!
I can finally create my own 5G router and have also VoLTE :)

**Comment by huanghitoy** [comment]
> hi@stich86 
> The status of your RM502Q-GL in asterisk-chan-quectel is free. The status of my RM500Q-GL is Not initia. Please advise.



Connected to Asterisk 20.5.2 currently running on R7800_op (pid = 32329)
R7800_op*CLI> quectel show devices
ID           Group State      RSSI Mode Provide Model          Firmware          IMEI             IMSI             Number
quectel0     0     Not initia 0    8    CMCC    RM500Q-GL      RM500QGLABR13A02M 863305040877218  460075585416901
R7800_op*CLI> quectel show de
device   devices
[Aug  8 11:47:32] WARNING[32340]: asterisk.c:3459 canary_thread: The canary is no more.  He has ceased to be!  He's expired and gone to meet his maker!  He's a stiff!  Bereft of life, he rests in peace.  His metabolic processes are now history!  He's off the twig!  He's kicked the bucket.  He's shuffled off his mortal coil, run down the curtain, and joined the bleeding choir invisible!!  THIS is an EX-CANARY.  (Reducing priority)
[Aug  8 11:47:32] WARNING[32340]: asterisk.c:1817 set_priority_all: Unable to set regular thread priority on main thread
R7800_op*CLI>  quectel show device
No such command ' quectel show device' (type 'core show help quectel show device' for other possible commands)
R7800_op*CLI>  quectel show device
No such command ' quectel show device' (type 'core show help quectel show device' for other possible commands)
R7800_op*CLI> show device state quectel0
No such command 'show device state quectel0' (type 'core show help show device' for other possible commands)
R7800_op*CLI> core show
No such command 'core show' (type 'core show help core show' for other possible commands)
R7800_op*CLI> core set verbose 5
Console verbose was 3 and is now 5.
R7800_op*CLI> quectel sms list received
No such command 'quectel sms list received' (type 'core show help quectel sms list received' for other possible commands)
R7800_op*CLI> quectel sms list received read
R7800_op*CLI>
Disconnected from Asterisk server
Asterisk cleanly ending (0).
Executing last minute cleanups
root@R7800_op:~#
