### ISSUE TITLE
Audio Quality Very Bad (SIM7600G-H)

### ISSUE THREAD

**Issue by blitz9826** [RoEdAl/asterisk-chan-quectel#18]
I've set the following commands:

AT+COUTGAIN=0
AT+CMICGAIN=0
AT+CECM=0

The audio quality is still poor for transmission. Receiving is fine. It sounds like the mic has gain applied to it, and the sound is muffled and blown out. I'd love to try setting the in-call-only variables somehow through a script that I can hook into Asterisk for each call made. Using FreePBX 17 Beta on Debian 12.

Thanks!

**Comment by RoEdAl** [comment]
From my experience setting all gains to zero is a **very bad** idea. A good starting point is described on [Wiki](https://github.com/RoEdAl/asterisk-chan-quectel/wiki/Improving-audio-quality) page:

```
AT+COUTGAIN=8
AT+CMICGAIN=3
```

then you may gradually change gain values. Every small change **requires testing**. And there are more AT commands to experiment with: `AT+CRXVOL`, `AT+CTXVOL`, `AT+CTXMICGAIN` etc.

It is also a good idea to turn off audio processing on *SIP Phone* you're using during testing. In particular, turn off AGC (automatic gain control) if possible.
