### ISSUE TITLE
Help compiling for OpenWrt Snapshot

### ISSUE THREAD

**Issue by stich86** [RoEdAl/asterisk-chan-quectel#19]
Hi @RoEdAl 

i'm tryting to compile chan-quectel for OpenWrt Snapshot (Banana BPI-R3-Mini, that is corrently not supported by 23.05).
I've compiled the SDK and followed instruction under openwrt folder, but it doesn't compile:

```
#
# No change to .config
#
make[1]: Entering directory '/home/lynx/5G_Router/Banana-BPI-R3-Mini/asterisk-chan-quectel/openwrt/openwrt-sdk-mediatek-filogic_gcc-13.2.0_musl.Linux-x86_64'
make[1]: *** No rule to make target 'package/asterisk-chan-quectel'.  Stop.
make[1]: Leaving directory '/home/lynx/5G_Router/Banana-BPI-R3-Mini/asterisk-chan-quectel/openwrt/openwrt-sdk-mediatek-filogic_gcc-13.2.0_musl.Linux-x86_64'
make: *** [/home/lynx/5G_Router/Banana-BPI-R3-Mini/asterisk-chan-quectel/openwrt/openwrt-sdk-mediatek-filogic_gcc-13.2.0_musl.Linux-x86_64/include/toplevel.mk:226: package/asterisk-chan-quectel] Error 2
```

Any suggestion?

Thanks in advance!

**Comment by RoEdAl** [comment]
Make backup of `.config` and `feeds.conf` (if exists) files:

```sh
mv .config .config.prev
mv feeds.conf feeds.conf.prev
```

and run `./build-opk.sh` script again.

**Comment by stich86** [comment]
so it doesn't compile against Asterisk 20.6.0

```
In file included from /usr/src/asterisk-20.6.0/include/asterisk.h:23,
                 from /root/asterisk-chan-quectel/install/openwrt/openwrt-sdk-mediatek-filogic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/asterisk-chan-quectel-2023.12.13-3-g9b9f5c-dirty/src/ast_config.h:10,
                 from /root/asterisk-chan-quectel/install/openwrt/openwrt-sdk-mediatek-filogic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/asterisk-chan-quectel-2023.12.13-3-g9b9f5c-dirty/src/app.c:5:
/usr/src/asterisk-20.6.0/include/asterisk/astmm.h:156:42: error: expected '=', ',', ';', 'asm' or '__attribute__' before '->' token
  156 |         Do_not_use_calloc__use_ast_calloc->fail(a, b)
      |                                          ^~
/usr/src/asterisk-20.6.0/include/asterisk/astmm.h:160:84: error: expected '=', ',', ';', 'asm' or '__attribute__' before '->' token
  160 |         Do_not_use_free__use_ast_free_or_ast_std_free_for_remotely_allocated_memory->fail(a)
      |                                                                                    ^~
In file included from /usr/src/asterisk-20.6.0/include/asterisk/vector.h:22,
                 from /usr/src/asterisk-20.6.0/include/asterisk/stringfields.h:178,
                 from /usr/src/asterisk-20.6.0/include/asterisk/app.h:26,
                 from /root/asterisk-chan-quectel/install/openwrt/openwrt-sdk-mediatek-filogic_gcc-13.2.0_musl.Linux-x86_64/build_dir/target-aarch64_cortex-a53_musl/asterisk-chan-quectel-2023.12.13-3-g9b9f5c-dirty/src/app.c:9:
/usr/src/asterisk-20.6.0/include/asterisk/lock.h:55:10: fatal error: execinfo.h: No such file or directory
   55 | #include <execinfo.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

i don't have any libexecinfo-dev for Debian :(

**Comment by RoEdAl** [comment]
I am able to build `chan_quectel` using SDK downloaded from [here](https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/). But in these snapshots [Asterisk v20.5.2-rc1](https://downloads.openwrt.org/snapshots/packages/aarch64_cortex-a53/telephony/) is used.

**Comment by RoEdAl** [comment]
Just use the same build environment as you used to build *Asterisk* packages. Installing header's files isn't an option for *OpenWRT*. In your environment just update `feeds.conf` (or `feeds.conf.default`) manually adding contents of `feeds-strskx.conf` file and refresh package's list:

```sh
./scripts/feeds update -a
./scripts/feeds install -a
./scripts/feeds install asterisk-chan-quectel
```

Then select `asterisk-chan-quectel` package manually using `make menuconfig` an build it:

```sh
make menuconfig
make package/asterisk-chan-quectel/clean
make package/asterisk-chan-quectel/compile
make package/index
```

**Comment by stich86** [comment]
so I can use my openwrt build env? No needs to use SDK right?

**Comment by RoEdAl** [comment]
Yes new SDK isn't required.
Use **geneated** `feeds-strskx.conf` file from **`install/openwrt`** directory:

```sh
git clone https://github.com/RoEdAl/asterisk-chan-quectel.git
./make-build-dir.cmake
./install-openwrt-makefile.cmake
cat install/openwrt/feeds-*.conf
```

**Comment by stich86** [comment]
> Yes new SDK isn't required. Use **geneated** `feeds-strskx.conf` file from **`install/openwrt`** directory:
> 
> ```shell
> git clone https://github.com/RoEdAl/asterisk-chan-quectel.git
> ./make-build-dir.cmake
> ./install-openwrt-makefile.cmake
> cat install/openwrt/feeds-*.conf
> ```

ok but the ./make-build-dir.cmake is trying to find the Asterisk header on my machine and not the one used in OpenWrt. Anyway it has created the feeds, but the module doesn't compile:

```
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-usb2 for asterisk-chan-quectel
 * pkg_hash_fetch_best_installation_candidate: Packages for asterisk-chan-quectel found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package asterisk-chan-quectel.
make[2]: *** [package/Makefile:71: package/install] Error 255
make[2]: Leaving directory '/home/lynx/5G_Router/Banana-BPI-R3-Mini/openwrt'
make[1]: *** [package/Makefile:124: /home/lynx/5G_Router/Banana-BPI-R3-Mini/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/lynx/5G_Router/Banana-BPI-R3-Mini/openwrt'
make: *** [/home/lynx/5G_Router/Banana-BPI-R3-Mini/openwrt/include/toplevel.mk:233: world] Error 2
```

**Comment by stich86** [comment]
ok looks like deps are not automatically selected, and i don't know why.. I was able to compile. Just a question:

how to put modem in "Free" State? On each reboot it's different... i need to start/stop the channel to make it "Free" instead of "Not Init".

I've also tried to change timeout form 30 to 60, but nothing to do. The module is also used for internet access from BPI-R3-Mini (over MIBM)

**Comment by RoEdAl** [comment]
You may try to access internet over NDIS or ECM device but **read documentation** before. Some additional packages should be installed and serial devices **may disappear**! 

* [Automated connection establishment with SIM7600 series modules when using RNDIS USB mode](https://techship.com/support/faq/how-to-automated-connection-establishment-with-sim7600-series-modules-when-using-rndis-usb-mode/),
* [More Networking with SIM7600G-H 4G HAT (B) for Raspberry Pi](https://wimsworld.wordpress.com/2022/07/16/more-networking-with-sim7600g-h-4g-hat-b-for-raspberry-pi/),
* [SIM7600X ECM Dial-Up Internet](https://www.waveshare.com/wiki/SIM7600X_ECM_Dail-up).

----

Try also to decrease `interval` value in `[general]` section of `quectel.conf` file.

Another solution may be to set `initstate=stop` in `quectel.conf` file and start modem (`asterisk -x 'quectel start...'`) with some delay.

**Comment by stich86** [comment]
i've just put a `sleep 10` into asterisk start-up binary :)
