### ISSUE TITLE
Received English SMS Messages are Chinese

### ISSUE THREAD

**Issue by mpmc** [RoEdAl/asterisk-chan-quectel#24]
Hi.

Yes it's me again (sorry!)

The module appears to be almost working as expected now using the clang-format branch (ref: #23), but it looks like receiving SMS is broken & displaying messages in random Chinese. Sending works OK (messages sent in Eng are received in Eng using the quectel sms command).

Here is an example.

```
  == [quectel0][SMS:0 TS:2024-05-21 15:00:32 +01:00] Got message part from +447*********: [䰀漀氀]
 [quectel0][SMS:0 PARTS:1 TS:2024-05-21 15:00:32 +01:00] Got message from +447*********: [䰀漀氀]

```
That is supposed to read "lol"

I connected to tty directly and sent a text to the module and then used https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-pdu-decoder/ to decode it and it shows the message in English.

To be sure it wasn't the phone I used, I sent another text from a different phone, network and number (Nokia dumb phone) and sadly the module outputs the messages in Chinese.

(While writing this) I just tried again but have the debug when receiving an sms, the only thing that stands out is..

```
[May 21 14:28:37] DEBUG[5718]: channel_internal_api.c:701 ast_channel_nativeformats_set:  <initializing>: Formats: (none)"
```
I cannot post that here as it contains private info in the PDU format.

Bit of an odd one!

**Comment by RoEdAl** [comment]
I'm aware of the issue. Currently I have serious problems with my computer which was used for testing and debugging so fixing this issue may take some time. Sorry for the inconvenience.

**Comment by mpmc** [comment]
> I'm aware of the issue. Currently I have serious problems with my computer which was used for testing and debugging so fixing this issue may take some time. Sorry for the inconvenience.

There is no need to apologise (you are doing this out of the kindness of your heart after all).

I have no issues waiting and happy to test anything if needed.

**Comment by RoEdAl** [comment]
OK. I am back. The question is: is the message wrongly displayed (logged) or/and wrongly decoded? Some issues with message logging were fixed so please switch to *master* branch (*clang-format* is gone) and perform some testing if you can. Check also `SMS` variable (JSON) in *dialplan*. Has the message (`msg`) the correct content in this variable?

**Comment by mpmc** [comment]
> OK. I am back. The question is: is the message wrongly displayed (logged) or/and wrongly decoded? Some issues with message logging were fixed so please switch to _master_ branch (_clang-format_ is gone) and perform some testing if you can. Check also `SMS` variable (JSON) in _dialplan_. Has the message (`msg`) the correct content in this variable?

Sorry for slow reply. Not been well. 

Sadly the json output is in Chinese too.

```
  == [quectel0][SMS:0 TS:2024-06-01 01:39:59 +01:00] Got message part from +444444444444: [䄀最愀椀渀]
 [quectel0][SMS:0 PARTS:1 TS:2024-06-01 01:39:59 +01:00] Got message from +444444444444: [䄀最愀椀渀]
    -- Executing [sms@incoming-mobile:1] NoOp("Local/sms@incoming-mobile-00000003;1", "SMS from device quectel0") in new stack
    -- Executing [sms@incoming-mobile:2] Verbose("Local/sms@incoming-mobile-00000003;1", "2, mpmc - 䄀最愀椀渀") in new stack
  ==  mpmc - 䄀最愀椀渀
    -- Executing [sms@incoming-mobile:3] System("Local/sms@incoming-mobile-00000003;1", "/bin/echo "{"ts":"2024-06-01 01:39:59 +01:00","parts":1,"from":"+444444444444","msg":"䄀最愀椀渀"}" > /tmp/test.txt") in new stack
    -- Executing [sms@incoming-mobile:4] Hangup("Local/sms@incoming-mobile-00000003;1", "") in new stack
  == Spawn extension (incoming-mobile, sms, 4) exited non-zero on 'Local/sms@incoming-mobile-00000003;1'
Min*CLI> exit
Asterisk cleanly ending (0).
Executing last minute cleanups
root@Min:/etc/asterisk# cat /tmp/test.txt 
{ts:2024-06-01 01:39:59 +01:00,parts:1,from:+444444444444,msg:䄀最愀椀渀}
```
```
root@Min:/etc/asterisk# cat extensions.conf 
[incoming-mobile]
exten => sms,1,NoOp(SMS from device ${JSON_DECODE(QUECTEL,name)})
same => n,Verbose(2, mpmc - ${JSON_DECODE(SMS,msg)})
same => n,System(/bin/echo "${SMS}" > /tmp/test.txt)
same => n,Hangup
```

**Comment by mpmc** [comment]
Oh I never did ask. Is this an issue for certain modem/modules (for example just the EC25) or just chan-quectel code as a whole?

**Comment by RoEdAl** [comment]
I think this is rather *chan-quectel* issue. Please try again with the latest changes on *master* branch. You may also experiment with `quectel sms direct on <device>` and `quectel sms direct off <device>` commands.

Unfortunately, I cannot reproduce such a situation with wrongly decoded SMS. I know you cannot show me a whole PDU but even screenshot of decoded PDU with hidden sensitive data will be useful.

**Comment by mpmc** [comment]
> I think this is rather _chan-quectel_ issue. Please try again with the latest changes on _master_ branch. You may also experiment with `quectel sms direct on <device>` and `quectel sms direct off <device>` commands.
> 
> Unfortunately, I cannot reproduce such a situation with wrongly decoded SMS. I **know you cannot show me a whole PDU but even screenshot of decoded PDU with hidden sensitive data will be useful.**

Ah, you misunderstand, I can absolutely send you a full PDU, just not in public! I will give it another go, with the latest code, but if it still doesn't work right, I'll send you a full asterisk debug log by email.

**Comment by mpmc** [comment]
Mail & log sent :)

**Comment by RoEdAl** [comment]
Thank you. I'm not quite sure but it may be endianness issue. I guess your hardware is big-endian. Am I right? If so, please try `chan_quectel` from *char-conv* branch.

**Comment by mpmc** [comment]
> Thank you. I'm not quite sure but it may be endianness issue. I guess your hardware is big-endian. Am I right? If so, please try `chan_quectel` from _char-conv_ branch.

I'll give it a try and report back in a few hours, currently in bed due to allergies!

I had suspected it might have been endianness as i saw you and another user mentioning it with the same device, GL-XE300 in discussions .

**Comment by mpmc** [comment]
Good news, it now decodes correctly!

```
  == [quectel0][SMS:0 TS:2024-06-07 17:10:17 +01:00] Got message part from +441234567890: [Debug]
 [quectel0][SMS:0 PARTS:1 TS:2024-06-07 17:10:17 +01:00] Got message from +441234567890: [Debug]
    -- Executing [sms@incoming-mobile:1] NoOp("Local/sms@incoming-mobile-00000000;1", "SMS from device quectel0") in new stack
    -- Executing [sms@incoming-mobile:2] Set("Local/sms@incoming-mobile-00000000;1", "SMS_TXT=Debug") in new stack
    -- Executing [sms@incoming-mobile:3] GotoIf("Local/sms@incoming-mobile-00000000;1", "1?smstxt:smsempty") in new stack
    -- Goto (incoming-mobile,sms,4)
    -- Executing [sms@incoming-mobile:4] Verbose("Local/sms@incoming-mobile-00000000;1", "2, [quectel0] Incoming SMS from +441234567890 [2024-06-07 17:10:17 +01:00]: Debug") in new stack
  ==  [quectel0] Incoming SMS from +441234567890 [2024-06-07 17:10:17 +01:00]: Debug
    -- Executing [sms@incoming-mobile:5] Goto("Local/sms@incoming-mobile-00000000;1", "smsbye") in new stack
    -- Goto (incoming-mobile,sms,7)
    -- Executing [sms@incoming-mobile:7] Hangup("Local/sms@incoming-mobile-00000000;1", "") in new stack
  == Spawn extension (incoming-mobile, sms, 7) exited non-zero on 'Local/sms@incoming-mobile-00000000;1'
```

Awesome! Many many thanks.

PS: You still haven't said what your PayPal is so I can at least send you a thanks. :)

**Comment by RoEdAl** [comment]
Thank you once again for your testing.
I've found old *Mikrotik* **951Ui-2HnD** which seems ideal device for testing: big endian platform, weak 1-core CPU, low RAM, USB port. It takes some time to install OpenWRT on it but finally it works.
