### ISSUE TITLE
No sound for both side !

### ISSUE THREAD

**Issue by CpServiceSpb** [RoEdAl/asterisk-chan-quectel#7]
Quectel channel with Asterisk 20.4.0 on Ubuntu 22.04 x64 LTS.
Sound over serial ttyUSB is used.
After AT+CFUN=1,1 (reboot the device) both-sides sounds was appeared, but error is remained:
`src/channel.c:135 channel_request: Asked to get a channel of unsupported format '(slin16)'`

And there is echo.
I tried to set "slin16" option to on/off or to disable it.
Nothing changed.

With sound set up to UAC, thtere is no echo, but one way sound.

**Comment by RoEdAl** [comment]
This is not an error but **warning**. You may safely ignore this message. `slin16` option is for *SimCom* modules only.

See also my wiki page: [Improving audio quality](https://github.com/RoEdAl/asterisk-chan-quectel/wiki/Improving-audio-quality).

Which side is available in UAC mode? What module are you using?

**Comment by CpServiceSpb** [comment]
Now there is no voice from inside to outside.
Module is EC25E.

**Comment by RoEdAl** [comment]
From modem to *Asterisk* or from modem to GSM network?

----

You can try to diagnose this problem in UAC mode by setting high debug level (6,7 and 8):

```
core set debug 6
```

This generates **a lot** of messages. Look for messages with `[ALSA]` (`[ALSA][CAPTURE]`, `[ALSA][PLAYBACK]`) string.

You may also rebuild `chan_quectel` with the latest changes. But these changes brings JSON-formatted variables so be careful.

**Comment by CpServiceSpb** [comment]
> Now there is no voice from inside to outside.
From internal phone to external ellular station (phone) .

> You can try to diagnose this problem in UAC mode by setting high debug level (6,7 and 8):
Ok. I will try.`
